#ifndef CARVE_FUN_DEFINE_H_
#define CARVE_FUN_DEFINE_H_

#if defined(__CLASS)
	#define by_MainProcess						 m_sc2_obj.MainProcess				
	#define by_LibraryInitial					 m_sc2_obj.LibraryInitial			
	#define by_LibraryDestroy					 m_sc2_obj.LibraryDestroy			
	#define by_LibrarySetDebug					 m_sc2_obj.LibrarySetDebug			
	#define by_GetLibraryMsg                     m_sc2_obj.GetLibraryMsg
	#define by_GetConnectionMsg                  m_sc2_obj.GetConnectionMsg
	#define by_GetConnectionError                m_sc2_obj.GetConnectionError
	#define by_LocalDetectControllers            m_sc2_obj.LocalDetectControllers
	#define by_LocalReadControllerCount          m_sc2_obj.LocalReadControllerCount
	#define by_LocalReadController               m_sc2_obj.LocalReadController
	#define by_ConnectSetPwd                     m_sc2_obj.ConnectSetPwd
	#define by_ConnectLocalList                  m_sc2_obj.ConnectLocalList
	#define by_ConnectLocalIP                    m_sc2_obj.ConnectLocalIP
	#define by_Disconnect                        m_sc2_obj.Disconnect
	#define by_FtpSetConnection                  m_sc2_obj.FtpSetConnection
	#define by_FtpGetFileList                    m_sc2_obj.FtpGetFileList
	#define by_FtpReadFileCount                  m_sc2_obj.FtpReadFileCount
	#define by_FtpReadFile                       m_sc2_obj.FtpReadFile
	#define by_FtpMakeDir                        m_sc2_obj.FtpMakeDir
	#define by_FtpUpload1File                    m_sc2_obj.FtpUpload1File
	#define by_FtpDownload1File                  m_sc2_obj.FtpDownload1File
	#define by_FtpDelete1File                    m_sc2_obj.FtpDelete1File
	#define by_FtpTransferFileReset              m_sc2_obj.FtpTransferFileReset
	#define by_FtpTransferFileAdd                m_sc2_obj.FtpTransferFileAdd
	#define by_FtpUploadFiles                    m_sc2_obj.FtpUploadFiles
	#define by_FtpDownloadFiles                  m_sc2_obj.FtpDownloadFiles
	#define by_FtpDeleteFiles                    m_sc2_obj.FtpDeleteFiles
	#define by_FtpCheckDone                      m_sc2_obj.FtpCheckDone
	#define by_FtpWaitDone                       m_sc2_obj.FtpWaitDone
	#define by_LocalGetFileList                  m_sc2_obj.LocalGetFileList
	#define by_LocalReadFileCount                m_sc2_obj.LocalReadFileCount
	#define by_LocalReadFile                     m_sc2_obj.LocalReadFile
	#define by_LocalDeleteFile                   m_sc2_obj.LocalDeleteFile
	#define by_memI                              m_sc2_obj.memI
	#define by_memO                              m_sc2_obj.memO
	#define by_memC                              m_sc2_obj.memC
	#define by_memS                              m_sc2_obj.memS
	#define by_memA                              m_sc2_obj.memA
	#define by_memR                              m_sc2_obj.memR
	#define by_memRBit                           m_sc2_obj.memRBit
	#define by_memRString                        m_sc2_obj.memRString
	#define by_memF                              m_sc2_obj.memF
	#define by_memRPtr                           m_sc2_obj.memRPtr
	#define by_memSetO                           m_sc2_obj.memSetO
	#define by_memSetC                           m_sc2_obj.memSetC
	#define by_memSetS                           m_sc2_obj.memSetS
	#define by_memSetA                           m_sc2_obj.memSetA
	#define by_memSetR                           m_sc2_obj.memSetR
	#define by_memSetRBit                        m_sc2_obj.memSetRBit
	#define by_memSetRString                     m_sc2_obj.memSetRString
	#define by_memSetF                           m_sc2_obj.memSetF
	#define by_GetTranState                      m_sc2_obj.GetTranState
	#define by_GetDataPointer                    m_sc2_obj.GetDataPointer
	#define by_LClearQueue                       m_sc2_obj.LClearQueue
	#define by_LReadBegin                        m_sc2_obj.LReadBegin
	#define by_LReadNI                           m_sc2_obj.LReadNI
	#define by_LReadNO                           m_sc2_obj.LReadNO
	#define by_LReadNC                           m_sc2_obj.LReadNC
	#define by_LReadNS                           m_sc2_obj.LReadNS
	#define by_LReadNA                           m_sc2_obj.LReadNA
	#define by_LReadNR                           m_sc2_obj.LReadNR
	#define by_LReadNF                           m_sc2_obj.LReadNF
	#define by_LReadEnd                          m_sc2_obj.LReadEnd
	#define by_LWriteBegin                       m_sc2_obj.LWriteBegin
	#define by_LWriteNO                          m_sc2_obj.LWriteNO
	#define by_LWriteNC                          m_sc2_obj.LWriteNC
	#define by_LWriteNS                          m_sc2_obj.LWriteNS
	#define by_LWriteNA                          m_sc2_obj.LWriteNA
	#define by_LWriteNR                          m_sc2_obj.LWriteNR
	#define by_LWriteNF                          m_sc2_obj.LWriteNF
	#define by_LWriteEnd                         m_sc2_obj.LWriteEnd
	#define by_DClearQueue                       m_sc2_obj.DClearQueue
	#define by_DWaitDone                         m_sc2_obj.DWaitDone
	#define by_DReadBegin                        m_sc2_obj.DReadBegin
	#define by_DReadNI                           m_sc2_obj.DReadNI
	#define by_DReadNO                           m_sc2_obj.DReadNO
	#define by_DReadNC                           m_sc2_obj.DReadNC
	#define by_DReadNS                           m_sc2_obj.DReadNS
	#define by_DReadNA                           m_sc2_obj.DReadNA
	#define by_DReadNR                           m_sc2_obj.DReadNR
	#define by_DReadNF                           m_sc2_obj.DReadNF
	#define by_DReadEnd                          m_sc2_obj.DReadEnd
	#define by_DWriteBegin                       m_sc2_obj.DWriteBegin
	#define by_DWrite1O                          m_sc2_obj.DWrite1O
	#define by_DWrite1C                          m_sc2_obj.DWrite1C
	#define by_DWrite1S                          m_sc2_obj.DWrite1S
	#define by_DWrite1A                          m_sc2_obj.DWrite1A
	#define by_DWrite1R                          m_sc2_obj.DWrite1R
	#define by_DWrite1F                          m_sc2_obj.DWrite1F
	#define by_DWrite1RBit                       m_sc2_obj.DWrite1RBit
	#define by_DWriteRString                     m_sc2_obj.DWriteRString
	#define by_DWriteNO                          m_sc2_obj.DWriteNO
	#define by_DWriteNC                          m_sc2_obj.DWriteNC
	#define by_DWriteNS                          m_sc2_obj.DWriteNS
	#define by_DWriteNA                          m_sc2_obj.DWriteNA
	#define by_DWriteNR                          m_sc2_obj.DWriteNR
	#define by_DWriteNF                          m_sc2_obj.DWriteNF
	#define by_DWriteEnd                         m_sc2_obj.DWriteEnd

#elif defined(__GCC)
	#define by_MainProcess						MainProcess				
	#define by_LibraryInitial					LibraryInitial			
	#define by_LibraryDestroy					LibraryDestroy			
	#define by_LibrarySetDebug					LibrarySetDebug			
	#define by_GetLibraryMsg                    GetLibraryMsg
	#define by_GetConnectionMsg                 GetConnectionMsg
	#define by_GetConnectionError               GetConnectionError
	#define by_LocalDetectControllers           LocalDetectControllers
	#define by_LocalReadControllerCount         LocalReadControllerCount
	#define by_LocalReadController              LocalReadController
	#define by_ConnectSetPwd                    ConnectSetPwd
	#define by_ConnectLocalList                 ConnectLocalList
	#define by_ConnectLocalIP                   ConnectLocalIP
	#define by_Disconnect                       Disconnect
	#define by_FtpSetConnection                 FtpSetConnection
	#define by_FtpGetFileList                   FtpGetFileList
	#define by_FtpReadFileCount                 FtpReadFileCount
	#define by_FtpReadFile                      FtpReadFile
	#define by_FtpMakeDir                       FtpMakeDir
	#define by_FtpUpload1File                   FtpUpload1File
	#define by_FtpDownload1File                 FtpDownload1File
	#define by_FtpDelete1File                   FtpDelete1File
	#define by_FtpTransferFileReset             FtpTransferFileReset
	#define by_FtpTransferFileAdd               FtpTransferFileAdd
	#define by_FtpUploadFiles                   FtpUploadFiles
	#define by_FtpDownloadFiles                 FtpDownloadFiles
	#define by_FtpDeleteFiles                   FtpDeleteFiles
	#define by_FtpCheckDone                     FtpCheckDone
	#define by_FtpWaitDone                      FtpWaitDone
	#define by_LocalGetFileList                 LocalGetFileList
	#define by_LocalReadFileCount               LocalReadFileCount
	#define by_LocalReadFile                    LocalReadFile
	#define by_LocalDeleteFile                  LocalDeleteFile
	#define by_memI                             memI
	#define by_memO                             memO
	#define by_memC                             memC
	#define by_memS                             memS
	#define by_memA                             memA
	#define by_memR                             memR
	#define by_memRBit                          memRBit
	#define by_memRString                       memRString
	#define by_memF                             memF
	#define by_memRPtr                          memRPtr
	#define by_memSetO                          memSetO
	#define by_memSetC                          memSetC
	#define by_memSetS                          memSetS
	#define by_memSetA                          memSetA
	#define by_memSetR                          memSetR
	#define by_memSetRBit                       memSetRBit
	#define by_memSetRString                    memSetRString
	#define by_memSetF                          memSetF
	#define by_GetTranState                     GetTranState
	#define by_GetDataPointer                   GetDataPointer
	#define by_LClearQueue                      LClearQueue
	#define by_LReadBegin                       LReadBegin
	#define by_LReadNI                          LReadNI
	#define by_LReadNO                          LReadNO
	#define by_LReadNC                          LReadNC
	#define by_LReadNS                          LReadNS
	#define by_LReadNA                          LReadNA
	#define by_LReadNR                          LReadNR
	#define by_LReadNF                          LReadNF
	#define by_LReadEnd                         LReadEnd
	#define by_LWriteBegin                      LWriteBegin
	#define by_LWriteNO                         LWriteNO
	#define by_LWriteNC                         LWriteNC
	#define by_LWriteNS                         LWriteNS
	#define by_LWriteNA                         LWriteNA
	#define by_LWriteNR                         LWriteNR
	#define by_LWriteNF                         LWriteNF
	#define by_LWriteEnd                        LWriteEnd
	#define by_DClearQueue                      DClearQueue
	#define by_DWaitDone                        DWaitDone
	#define by_DReadBegin                       DReadBegin
	#define by_DReadNI                          DReadNI
	#define by_DReadNO                          DReadNO
	#define by_DReadNC                          DReadNC
	#define by_DReadNS                          DReadNS
	#define by_DReadNA                          DReadNA
	#define by_DReadNR                          DReadNR
	#define by_DReadNF                          DReadNF
	#define by_DReadEnd                         DReadEnd
	#define by_DWriteBegin                      DWriteBegin
	#define by_DWrite1O                         DWrite1O
	#define by_DWrite1C                         DWrite1C
	#define by_DWrite1S                         DWrite1S
	#define by_DWrite1A                         DWrite1A
	#define by_DWrite1R                         DWrite1R
	#define by_DWrite1F                         DWrite1F
	#define by_DWrite1RBit                      DWrite1RBit
	#define by_DWriteRString                    DWriteRString
	#define by_DWriteNO                         DWriteNO
	#define by_DWriteNC                         DWriteNC
	#define by_DWriteNS                         DWriteNS
	#define by_DWriteNA                         DWriteNA
	#define by_DWriteNR                         DWriteNR
	#define by_DWriteNF                         DWriteNF
	#define by_DWriteEnd                        DWriteEnd

#else
#endif

#endif